# Generated by Django 5.2.8 on 2025-12-02 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('position', models.CharField(choices=[('CHAIRMAN', 'Barangay Chairman'), ('KAGAWAD', 'Barangay Kagawad'), ('SECRETARY', 'Barangay Secretary'), ('TREASURER', 'Barangay Treasurer'), ('SK_CHAIRMAN', 'SK Chairman')], max_length=50, verbose_name='Position')),
                ('committee', models.CharField(blank=True, help_text='e.g., Committee on Peace and Order', max_length=100, verbose_name='Committee')),
                ('induction_date', models.DateField(verbose_name='Induction Date')),
                ('term_end_date', models.DateField(blank=True, null=True, verbose_name='Term End Date')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='officials_photos/', verbose_name='Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Official',
                'verbose_name_plural': 'Officials',
                'ordering': ['position', 'last_name'],
            },
        ),
    ]
