# Generated by Django 5.2.8 on 2025-12-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Project Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Budget')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('target_end_date', models.DateField(verbose_name='Target End Date')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Actual End Date')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ON_GOING', 'On-Going'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='NOT_STARTED', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-start_date'],
            },
        ),
    ]
