# Generated by Django 5.2.8 on 2025-12-02 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlotterCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('NEIGHBORHOOD', 'Neighborhood Conflict'), ('LAND', 'Land Dispute'), ('COLLECTION', 'Collection of Debt'), ('DAMAGES', 'Property Damage'), ('VEXATION', 'Unjust Vexation'), ('OTHERS', 'Others')], max_length=20, verbose_name='Case Type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / On-Going'), ('SETTLED', 'Amicably Settled'), ('FILED_ACTION', 'Certificate to File Action Issued'), ('DISMISSED', 'Dismissed / Withdrawn')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('incident_date', models.DateTimeField(verbose_name='Date of Incident')),
                ('incident_place', models.CharField(max_length=255, verbose_name='Place of Incident')),
                ('narrative', models.TextField(verbose_name='Narrative of Incident')),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to='residents.resident')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_received', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Blotter Case',
                'verbose_name_plural': 'Blotter Cases',
                'ordering': ['-date_filed'],
            },
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Hearing Date')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks / Outcome')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='blotter.blottercase')),
            ],
            options={
                'verbose_name': 'Hearing',
                'verbose_name_plural': 'Hearings',
                'ordering': ['date'],
            },
        ),
    ]
