# Generated by Django 5.2.8 on 2025-12-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sex')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('contact_number', models.CharField(blank=True, max_length=20, verbose_name='Contact Number')),
                ('classification', models.CharField(choices=[('CHILD', 'Child (0-14)'), ('YOUTH', 'Youth (15-30)'), ('SENIOR', 'Senior Citizen (60+)'), ('INDIGENT', 'Indigent'), ('PWD', 'Person with Disability'), ('NONE', 'Not Classified')], default='NONE', max_length=20, verbose_name='Classification')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='residents_photos/', verbose_name='Photo')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this resident should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
