# Generated by Django 5.2.8 on 2025-12-02 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_number', models.CharField(max_length=50, unique=True, verbose_name='Household Number')),
                ('street_address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('housing_material', models.CharField(choices=[('CONCRETE', 'Concrete'), ('SEMI_CONCRETE', 'Semi-Concrete'), ('LIGHT', 'Light Materials'), ('SALVAGED', 'Salvaged Materials')], default='CONCRETE', max_length=20, verbose_name='Housing Material')),
                ('ownership_status', models.CharField(choices=[('OWNED', 'Owned'), ('RENTED', 'Rented'), ('SHARER', 'Sharer / Living with Relatives'), ('INFORMAL', 'Informal Settler')], default='OWNED', max_length=20, verbose_name='Ownership Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resident',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='resident',
            name='relationship_to_head',
            field=models.CharField(blank=True, choices=[('HEAD', 'Head of Family'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other Relative/Non-Relative')], max_length=20, verbose_name='Relationship to Head'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='classification',
            field=models.CharField(choices=[('CHILD', 'Child (0-14)'), ('YOUTH', 'Youth (15-30)'), ('SENIOR', 'Senior Citizen (60+)'), ('PWD', 'Person with Disability'), ('INDIGENT', 'Indigent'), ('NONE', 'Not Classified')], default='NONE', max_length=20, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='resident',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='residents.household'),
        ),
    ]
