# Generated by Django 5.2.8 on 2025-12-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Barangay BIMS', max_length=255, verbose_name='Barangay Name')),
                ('city_municipality', models.CharField(blank=True, max_length=255, verbose_name='City/Municipality')),
                ('province', models.CharField(blank=True, max_length=255, verbose_name='Province')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Region')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='barangay_assets/', verbose_name='Logo')),
                ('vision', models.TextField(default='To be a model barangay...', verbose_name='Vision')),
                ('mission', models.TextField(default='To provide quality services...', verbose_name='Mission')),
                ('service_pledge', models.TextField(default='We commit to deliver efficient public service...', verbose_name='Service Pledge')),
                ('contact_number', models.CharField(blank=True, max_length=50, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
            ],
            options={
                'verbose_name': 'Barangay Information',
                'verbose_name_plural': 'Barangay Information',
            },
        ),
    ]
