# Generated by Django 5.2.8 on 2025-12-02 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CLEARANCE', 'Barangay Clearance'), ('INDIGENCY', 'Certificate of Indigency'), ('RESIDENCY', 'Certificate of Residency'), ('BUSINESS', 'Business Clearance')], max_length=20, verbose_name='Document Type')),
                ('purpose', models.CharField(max_length=255, verbose_name='Purpose')),
                ('or_number', models.CharField(blank=True, help_text='Official Receipt Number if applicable', max_length=50, verbose_name='OR Number')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid')),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='residents.resident')),
            ],
            options={
                'verbose_name': 'Document Request',
                'verbose_name_plural': 'Document Requests',
                'ordering': ['-date_issued'],
            },
        ),
    ]
